name: Merge PHP App to Another Branch

on:
  push:
    branches:
      - main # Replace with the name of your source branch

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v2
        with:
          ref: main # Replace with the name of your source branch

      - name: Configure git
        run: |
          git config --global user.name "alex.etne"
          git config --global user.email "alexandre.etienne05@gmail.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout target branch
        run: git checkout dev # Replace with the name of your target branch

      - name: Merge source branch into target branch
        run: git merge main # Replace with the name of your source branch

      - name: Push changes
        run: git push origin dev # Replace with the name of your target branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
